/**
 * This file auto generated by Imager
 * @address https://github.com/BCsl/RNImageManager
 * @author HelloCsl
 */
export default {
    common: {
        banner: require('./image/common/banner.png'),
        ic_arrow_back_black: require('./image/common/ic_arrow_back_black.png'),
        ic_close: require('./image/common/ic_close.png'),
        ic_default_avatar: require('./image/common/ic_default_avatar.png'),
        ic_info_outline: require('./image/common/ic_info_outline.png'),
        ic_like: require('./image/common/ic_like.png'),
        ic_logo: require('./image/common/ic_logo.png'),
        ic_menu_black: require('./image/common/ic_menu_black.png'),
        ic_more_vert_black: require('./image/common/ic_more_vert_black.png'),
        ic_notifications_black: require('./image/common/ic_notifications_black.png'),
        ic_open_in_browser: require('./image/common/ic_open_in_browser.png'),
        ic_search_black: require('./image/common/ic_search_black.png'),
        ic_settings_black: require('./image/common/ic_settings_black.png'),
        ic_share: require('./image/common/ic_share.png'),
    },
}

