/**
 * Created by chensuilun on 2017/9/1.
 */
//主题列表
export const TYPE_TOPIC_REFRESH_SUC = 'TYPE_TOPIC_REFRESH_SUC';
export const TYPE_TOPIC_REFRESH_ERR = 'TYPE_TOPIC_REFRESH_ERR';
export const TYPE_TOPIC_REFRESHING = 'TYPE_TOPIC_REFRESHING';
export const TYPE_TOPIC_LOADING_MORE = 'TYPE_TOPIC_LOADING_MORE';
export const TYPE_TOPIC_LOAD_MORE_ERR = 'TYPE_TOPIC_LOAD_MORE_ERR';
export const TYPE_TOPIC_LOAD_MORE_SUC = 'TYPE_TOPIC_LOAD_MORE_SUC';
//主题详情
export const TYPE_TOPIC_DETAIL_LOADING = 'TYPE_TOPIC_DETAIL_LOADING';
export const TYPE_TOPIC_DETAIL_ERROR = 'TYPE_TOPIC_DETAIL_ERROR';
export const TYPE_TOPIC_DETAIL_SUC = 'TYPE_TOPIC_DETAIL_SUC';
//主题回复
export const TYPE_TOPIC_RELIES_LOADING = 'TYPE_TOPIC_RELIES_LOADING';
export const TYPE_TOPIC_RELIES_ERROR = 'TYPE_TOPIC_RELIES_ERROR';
export const TYPE_TOPIC_RELIES_SUC = 'TYPE_TOPIC_RELIES_SUC';
export const TYPE_TOPIC_RELIES_LOAD_MORE_SUC = 'TYPE_TOPIC_RELIES_LOAD_MORE_SUC';

//新闻列表
export const TYPE_NEWS_REFRESH_SUC = 'TYPE_NEWS_REFRESH_SUC';
export const TYPE_NEWS_REFRESH_ERR = 'TYPE_NEWS_REFRESH_ERR';
export const TYPE_NEWS_REFRESHING = 'TYPE_NEWS_REFRESHING';
export const TYPE_NEWS_LOADING_MORE = 'TYPE_NEWS_LOADING_MORE';
export const TYPE_NEWS_LOAD_MORE_ERR = 'TYPE_NEWS_LOAD_MORE_ERR';
export const TYPE_NEWS_LOAD_MORE_SUC = 'TYPE_NEWS_LOAD_MORE_SUC';